version: '3.8'

services:
  run-api-locally:
    depends_on:
      - deepstroy-api

  deepstroy-api:
    build:
      context: .
    command: poetry run flask run
    volumes:
      - .:/app-workspace
    ports:
      - "7501:5000"
    env_file:
      - .env

  deepstroy-api-postgres:
    env_file:
      - .env
    ports:
      - "7510:5432"
