"""add-is-modeling-field

Revision ID: 52c9e2c0f2e9
Revises: 74918e37c010
Create Date: 2023-06-24 20:23:21.536994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c9e2c0f2e9'
down_revision = '74918e37c010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasting_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isModeling', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasting_files', schema=None) as batch_op:
        batch_op.drop_column('isModeling')

    # ### end Alembic commands ###
