"""add-forecasting-files-table

Revision ID: 74918e37c010
Revises: 
Create Date: 2023-06-24 10:34:59.708506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74918e37c010'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasting_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=2048), nullable=False),
    sa.Column('date_of_upload', sa.DateTime(), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecasting_files')
    # ### end Alembic commands ###
