"""add-is-modeling-column

Revision ID: ba43a828acef
Revises: 
Create Date: 2023-06-24 19:02:14.831306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba43a828acef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasting_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=2048), nullable=False),
    sa.Column('date_of_upload', sa.DateTime(), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('isModeling', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecasting_files')
    # ### end Alembic commands ###
